### ISSUE TITLE
Will not compile, some files are missing

### ISSUE THREAD

**Issue by randy909** [cy6erGn0m/kotlin-rxokhttp-websocket#1]
JetWebSocket appears to be missing, possibly others. This is a useful example as I'm working on something quite similar so I'd love to see the whole thing.

**Comment by cy6erGn0m** [comment]
Let me check, it is a little outdated

**Comment by cy6erGn0m** [comment]
@randy909 should be fixed now

**Comment by cy6erGn0m** [comment]
@randy909 you can try it with https://jitpack.io/#cy6erGn0m/kotlin-rxokhttp-websocket/0.0.1

**Comment by randy909** [comment]
Working great! Thank you very much!

**Comment by cy6erGn0m** [comment]
@randy909 good to see you use it. Let me know if you have ideas to improve it
